### ISSUE TITLE
Bot wont work whatsoever no matter what.

### ISSUE THREAD

**Issue by aarock1234** [1fge/open-supreme#1]
This is a regular supreme bot, but you never address pooky? Why is that? Pooky is what blocks your checkout, and if its not addressed then the bot will never work.

**Comment by 1fge** [comment]
Let’s start with the title. The bot works very well the majority of time aside from initial drops and some restocks, hence what’s written in the description. If you spent the same time amount of time reading the documentation that you did leaving comments on GitHub and reddit, you would see that very clearly what it’s meant to do, no secrets. 

Now, why doesn’t it include a pooky bypass? Because pooky bypasses are worth $10,000 upward and doesn’t fall into the scope of a free bot. The best part is it’s an open sourced project so YOU could go ahead and implement a pooky bypass if you feel so inclined, but I can’t really see that happening. 

The fact that you’re so upset over a free program on GitHub is astounding to me. What open source projects have you created recently?
